set cpu 11/34
;set cpu fpp
set cpu 64K
; set throttle 4M

attach ptr /Users/damien/Developer/AI/ATTN11/COREFORMER/PDP-11/tmp.f


;att RK0 rtv4_rk.dsk
att RK0 CORFMR.RK0
echo ------------------------
boot rk0
