reset
set cpu 32k
attach dsk0 dms.dsk

; log file
attach prt out.lst

; build functions
boot dsk
attach cr FUNCS.F
set cr 026F
go

; build coreformer and run it
boot dsk
attach cr CORFM.F
set cr 026F
go

quit


